// <auto-generated />
using System;
using BibliotekaFilmow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotekaFilmow.Migrations
{
    [DbContext(typeof(BibliotekaContext))]
    [Migration("20250205134621_DodajKomentarze")]
    partial class DodajKomentarze
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("BibliotekaFilmow.Komentarz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("TEXT");

                    b.Property<int>("PozycjaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tresc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PozycjaId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Komentarze");
                });

            modelBuilder.Entity("BibliotekaFilmow.Pozycja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gatunek")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategoria")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Obejrzane")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rezyser")
                        .HasColumnType("TEXT");

                    b.Property<int>("RokWydania")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tytul")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pozycje");
                });

            modelBuilder.Entity("BibliotekaFilmow.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyAdministrator")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("BibliotekaFilmow.Komentarz", b =>
                {
                    b.HasOne("BibliotekaFilmow.Pozycja", "Pozycja")
                        .WithMany("Komentarze")
                        .HasForeignKey("PozycjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliotekaFilmow.Uzytkownik", "Uzytkownik")
                        .WithMany("Komentarze")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pozycja");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("BibliotekaFilmow.Pozycja", b =>
                {
                    b.Navigation("Komentarze");
                });

            modelBuilder.Entity("BibliotekaFilmow.Uzytkownik", b =>
                {
                    b.Navigation("Komentarze");
                });
#pragma warning restore 612, 618
        }
    }
}
